console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
template = '❯❯ '
foreground = 'magenta'
background = 'transparent'

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]

[[tooltips]]
type = "git"
tips = ["git", "g"]
style = "diamond"
foreground = "#193549"
background = "#FFC300"
leading_diamond = ""
trailing_diamond = ""
template = "{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}"

[tooltips.properties]
fetch_status = true
fetch_upstream_icon = true

[[tooltips]]
type = "kubectl"
tips = ["k", "kubectl"]
style = "diamond"
leading_diamond = ""
trailing_diamond = ""
background = '#326CE5'
foreground = '#FFFFFF'
template = '⎈ {{ .Context }}{{ if .Namespace }}:{{ .Namespace }}{{ end }}'

[tooltips.properties]
fetch_status = true
fetch_upstream_icon = true

[[tooltips]]
type = "az"
tips = ["az", "terraform"]
style = "diamond"
leading_diamond = ""
trailing_diamond = ""
foreground = "#193549"
background = "#3CCBF4"
# template = " {{ .Name }}"
template = ' {{ .Name }}{{ if not (contains .EnvironmentName "AzureCloud") }} {{ .EnvironmentName }}{{ end }} '

[[tooltips]]
type = "aws"
tips = ["aws"]
style = "diamond"
leading_diamond = ""
trailing_diamond = ""
foreground = "#000000"
background = "#FF9900"
template = "{{.Profile}}{{if .Region}}@{{.Region}}{{end}} "

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '{{ .Path }}'
foreground = 'blue'
background = 'transparent'
type = 'path'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
style = 'full'

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
template = '{{ .FormattedMs }}'
foreground = 'yellow'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
background = 'transparent'
type = 'text'
style = 'plain'
foreground_templates = [
  '{{if gt .Code 0}}red{{end}}',
  '{{if eq .Code 0}}magenta{{end}}',
]

[blocks.segments.properties]
cache_duration = 'none'
